version: '3.8'

services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: 
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:
